#ifndef WARM_PREDEFINE_H_
#define WARM_PREDEFINE_H_

/*
    Those macro should defined by compiler
 */

#define BUILD_PREPROCESSOR_DEFINE_ERROR_STRING "Unknown, the preprocessor maybe errored"

#ifndef BUILD_VERSION_STRING
#define BUILD_VERSION_STRING BUILD_PREPROCESSOR_DEFINE_ERROR_STRING
#endif

#ifndef BUILD_GIT_REPO_INFO_STRING
#define BUILD_GIT_REPO_INFO_STRING BUILD_PREPROCESSOR_DEFINE_ERROR_STRING
#endif

#ifndef BUILD_DATE_STRING
#define BUILD_DATE_STRING BUILD_PREPROCESSOR_DEFINE_ERROR_STRING
#endif

#endif
