name: Build for Windows

on:
  workflow_dispatch:
    inputs:
      build_type:
        required: true
        default: "build_type=CI"

defaults:
  run:
    shell: msys2 {0}
    working-directory: ./source/

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: git make mingw-w64-x86_64-clang mingw-w64-x86_64-ncurses
    - name: Soft link ncurses header
      run: ln -s /mingw64/include/ncursesw/ncurses.h /mingw64/include/ncurses.h
    - name: make
      run: make warmaShark-Windows.exe ${{ inputs.build_type || 'build_type=CI' }}
    - name: Upload executable file
      uses: actions/upload-artifact@v4
      with:
        name: warmaShark-Windows.exe
        path: source/warmaShark-Windows.exe
        retention-days: 7
